07. Software Development/Solutions/Movie Mania/MovieMania/Models/AppUser.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MovieMania.Models
{
    public class AppUser:IdentityUser
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
     
    }
}

07. Software Development/Solutions/Movie Mania/MovieMania/Models/Comment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace MovieMania.Models
{
    public class Comment
    {
        [Key]
        public string Id { get; set; }
        [ForeignKey("UserId")]
        public string UserId { get; set; }
        [ForeignKey("FilmId")]
        public string FilmId { get; set; }
        public DateTime Time { get; set; }
        public string Content { get; set; }
    }
}

07. Software Development/Solutions/Movie Mania/MovieMania/Models/ErrorViewModel.cs
using System;

namespace MovieMania.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

07. Software Development/Solutions/Movie Mania/MovieMania/Models/Film.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MovieMania.Models
{
    public class Film
    {
        [Key]
        public string FilmId { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        public string Description { get; set; }
        [Required]
        public string Genre { get; set; }
        [Required]
        [Range(1, 5)]
        public int Rating { get; set; }
        [Required]
        public string ImageUrl { get; set; }
        [Required]
        public string TrailerUrl { get; set; }
        public List<Comment> Comment { get; set; }
    }
}

07. Software Development/Solutions/Movie Mania/MovieMania/Controllers/CatalogController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MovieMania.Data;
using MovieMania.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieMania.Controllers
{
    public class CatalogController : Controller
    {
        private readonly ApplicationDbContext _db;

        public CatalogController(ApplicationDbContext db)
        {
            _db = db;
        }

        [Authorize]
        public IActionResult CatalogIndex(string sortOrder, string searchString)
        {
            ViewBag.TitleSortOrder = String.IsNullOrEmpty(sortOrder) ? "title_desc" : "";
            ViewBag.DescriptionSortOrder = String.IsNullOrEmpty(sortOrder) ? "description_desc" : "";
            ViewBag.GenreSortOrder = String.IsNullOrEmpty(sortOrder) ? "genre_desc" : "";
            ViewBag.RatingSortOrder = String.IsNullOrEmpty(sortOrder) ? "rating_desc" : "";
            ViewData["CurrentFilter"] = searchString;

            var Films = from f in _db.Film select f;

            if(!String.IsNullOrEmpty(searchString))
            {
                Films = Films.Where(f => f.Title.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "title_desc":
                    Films = Films.OrderByDescending(b => b.Title);
                    break;
                case "description_desc":
                    Films = Films.OrderByDescending(b => b.Description);
                    break;
                case "genre_desc":
                    Films = Films.OrderByDescending(b => b.Genre);
                    break;
                case "rating_desc":
                    Films = Films.OrderByDescending(b => b.Rating);
                    break;
                default:
                    Films = Films.OrderBy(b => b.Title);
                    break;
            }

            return View(Films);
        }

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Add(Film film)
        {
            if(ModelState.IsValid)
            {
                film.FilmId = Guid.NewGuid().ToString();
                _db.Film.Add(film);
                _db.SaveChanges();

                TempData["FilmSuccessMessage"] = "Film was added successfully!";
                return RedirectToAction("CatalogIndex");
            }

            return View(film);
        }

        public IActionResult Delete(string id)
        {
            if (id == null || id == "")
            {
                return NotFound();
            }

            var film = _db.Film.Find(id);

            if(film == null)
            {
                return NotFound();
            }

            ViewBag.Film = film;
            return View(film);
        }

        public IActionResult DeleteFilm(string id)
        {
            var film = _db.Film.Where(el => el.FilmId == id).Single();

            if(film == null)
            {
                return NotFound();
            }

            _db.Film.Remove(film);
            _db.SaveChanges();

            TempData["FilmDeleteMessage"] = "Film was deleted successfully!";
            return RedirectToAction("CatalogIndex");
        }

        public IActionResult Edit(string id)
        {
            if(id == null || id == "")
            {
                return NotFound();
            }

            var film = _db.Film.Find(id);

            if(film == null)
            {
                return NotFound();
            }    

            ViewBag.Film = film;
            return View(film);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Film film)
        {
            if(ModelState.IsValid)
            {
                _db.Film.Update(film);
                _db.SaveChanges();

                TempData["FilmEditMessage"] = "Film was edited successfully!";
                return RedirectToAction("CatalogIndex");
            }

            return View(film);
        }

        public IActionResult Film(string id)
        {
            var film = _db.Film.Where(el => el.FilmId == id).Single();
            ViewBag.Film = film;
            return View(film);
        }

        public IActionResult AddComment(Comment comment)
        {
            if (ModelState.IsValid)
            {
                _db.Comment.Add(comment);
                _db.SaveChanges();

                TempData["FilmSuccessMessage"] = "Film was added successfully!";
                return RedirectToAction("CatalogIndex");
            }

            return RedirectToAction("Film");
        }

        public IActionResult Comments()
        {
            return View();
        }
    }
}

07. Software Development/Solutions/Movie Mania/MovieMania/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieMania.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Privacy()
        {
            return View();
        }
    }
}

07. Software Development/Solutions/Movie Mania/MovieMania/Views/Catalog/Add.cshtml
@model MovieMania.Models.Film
@{
    ViewData["Title"] = "Add Film";
}

<form method="post" asp-action="Add">
    <div class="border p-3">

        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
        <div class="form-group row">
            <h2 class="text-info pl-3">Add Movie</h2>
        </div>

        <div class="row">
            <div class="col-8">

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Title"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Title" class="form-control" />
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Description"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Description" class="form-control" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Genre"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Genre" class="form-control" />
                        <span asp-validation-for="Genre" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Rating"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Rating" class="form-control" />
                        <span asp-validation-for="Rating" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="ImageUrl"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="ImageUrl" class="form-control" />
                        <span asp-validation-for="ImageUrl" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="TrailerUrl"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="TrailerUrl" class="form-control" />
                        <span asp-validation-for="TrailerUrl" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Add" />
                        </div>

                        <div class="col">
                            <a asp-action="CatalogIndex" class="btn btn-success w-100"><i class="fas fa-sign-out-alt"></i>Back</a>
                        </div>

                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>

</form>

@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

07. Software Development/Solutions/Movie Mania/MovieMania/Views/Catalog/CatalogIndex.cshtml
@model IEnumerable<MovieMania.Models.Film>
@{
    ViewData["Title"] = "Films";
}

<div class="container">
    @if ((string)TempData["FilmSuccessMessage"] == "Film was added successfully!")
    {
        <div class="alert alert-success text-center w-100">Film was added successfully!</div>
    }
    else if ((string)TempData["FilmDeleteMessage"] == "Film was deleted successfully!")
    {
        <div class="alert alert-success text-center w-100">Film was deleted successfully!</div>
    }
    else if ((string)TempData["FilmEditMessage"] == "Film was edited successfully!")
    {
        <div class="alert alert-success text-center w-100">Film was edited successfully!</div>
    }

    <div class="row">
        <div class="col text-left">
            <a asp-controller="Catalog" asp-action="Add" class="btn btn-primary">Add New Movie</a>
        </div>
        <div class="col text-center">
            <p>
                Sort by:
                <a asp-action="CatalogIndex" asp-route-sortOrder="@ViewBag.TitleSortOrder">Title</a>,
                <a asp-action="CatalogIndex" asp-route-sortOrder="@ViewBag.DescriptionSortOrder">Description</a>,
                <a asp-action="CatalogIndex" asp-route-sortOrder="@ViewBag.GenreSortOrder">Genre</a>,
                <a asp-action="CatalogIndex" asp-route-sortOrder="@ViewBag.RatingSortOrder">Rating</a>
            </p>
            @*<div class="dropdown">
                    <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                        Sort by
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                        <li class="dropdown-item"><a asp-action="CatalogIndex" asp-route-sortOrder="@ViewBag.TitleSortOrder">Title</a></li>
                        <li class="dropdown-item"><a asp-action="CatalogIndex" asp-route-sortOrder="@ViewBag.DescriptionSortOrder">Description</a></li>
                        <li class="dropdown-item"><a asp-action="CatalogIndex" asp-route-sortOrder="@ViewBag.GenreSortOrder">Genre</a></li>
                        <li class="dropdown-item"><a asp-action="CatalogIndex" asp-route-sortOrder="@ViewBag.RatingSortOrder">Rating</a></li>
                    </ul>
                </div>*@
        </div>
        <div class="col text-right">
            <form class="form-inline my-2 my-lg-0" method="get" asp-action="CatalogIndex">
                <input class="form-control mr-sm-2" type="search" placeholder="Search by name..." aria-label="Search" name="SearchString" value="@ViewData["CurrentFilter"]" />
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit" asp-action="CatalogIndex">Search</button>
            </form>
        </div>
    </div>

    <br />

    <div class="row text-center">
        <div class="container">
            <div class="row">
                @if (Model.Count() > 0)
                {
                    @foreach (var obj in Model)
                    {
                        <div class="col text-center">
                            <div class="card" style="width: 19rem;">
                                <img class="card-img-top" src="@obj.ImageUrl" alt="Card image cap">
                                <div class="card-body">
                                    <h5 class="card-title">"@obj.Title" - @obj.Genre</h5>
                                    <p class="card-text">
                                        @obj.Rating &#11088;
                                    </p>
                                    <a asp-controller="Catalog" asp-route-Id="@obj.FilmId" asp-action="Film" class="btn btn-primary">Details</a>
                                    <a asp-controller="Catalog" asp-route-Id="@obj.FilmId" asp-action="Edit" class="btn btn-warning">Edit</a>
                                    <a asp-controller="Catalog" asp-route-Id="@obj.FilmId" asp-action="Delete" class="btn btn-danger">Delete</a>
                                </div>
                            </div> <br />
                        </div>
                    }
                }
                else
                {
                    <br /><p>No movies to display.</p><br />
                }
            </div>
        </div>
    </div>
</div>

07. Software Development/Solutions/Movie Mania/MovieMania/Views/Catalog/Comments.cshtml
@{
    ViewData["Title"] = "Comments";
}

<h1>Comming soon...</h1>

07. Software Development/Solutions/Movie Mania/MovieMania/Views/Catalog/Delete.cshtml
@model MovieMania.Models.Film
@{
    ViewData["Title"] = "Delete Film";
}

<form method="post" asp-action="DeleteFilm">
    <input asp-for="FilmId" hidden />
    <h1 class="text-center">Are you sure that you want to delete "@ViewBag.Film.Title"?</h1>
    <div class="col text-center">
        <a asp-controller="Catalog" asp-route-Id="@ViewBag.Film.FilmId" asp-action="DeleteFilm" class="btn btn-danger">Yes, I am sure!</a>
        <a asp-action="CatalogIndex" class="btn btn-primary"><i class="fas fa-sign-out-alt"></i>No, bring me back!</a>
    </div>
</form>

@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

07. Software Development/Solutions/Movie Mania/MovieMania/Views/Catalog/Edit.cshtml
@model MovieMania.Models.Film
@{
    ViewData["Title"] = "Edit Film";
}

<form method="post">
    <input asp-for="FilmId" hidden />
    <div class="border p-3">

        <div class="form-group row">
            <h2 class="text-info pl-3">Edit Film</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Title"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Title" class="form-control" />
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Description"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Description" class="form-control" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Genre"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Genre" class="form-control" />
                        <span asp-validation-for="Genre" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Rating"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Rating" class="form-control" />
                        <span asp-validation-for="Rating" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="ImageUrl"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="ImageUrl" class="form-control" />
                        <span asp-validation-for="ImageUrl" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="TrailerUrl"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="TrailerUrl" class="form-control" />
                        <span asp-validation-for="TrailerUrl" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Edit" />
                        </div>
                        <div class="col">
                            <a asp-action="CatalogIndex" class="btn btn-success w-100"><i class="fas fa-sign-out-alt"></i> Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>

</form>

@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

07. Software Development/Solutions/Movie Mania/MovieMania/Views/Catalog/Film.cshtml
@{
    ViewData["Title"] = "Film";
}

<div class="row">

    <div class="col text-center">
        <div style="width: 400px;" class="card">
            <img src="@ViewBag.Film.ImageUrl" class="card-img-top" alt="...">
            <div class="card-body">
                <h1 class="text-center">"@ViewBag.Film.Title"</h1>
                <h2 class="text-center"> @ViewBag.Film.Rating &#11088;</h2>
            </div>
        </div>
    </div>

    <div class="col text-center">
        <div>
            <a href="@ViewBag.Film.TrailerUrl" class="btn btn-primary">Trailer</a>
            <a asp-action="CatalogIndex" class="btn btn-success"><i class="fas fa-sign-out-alt"></i>Back</a>
            <a asp-action="Comments" class="btn btn-info"><i class="fas fa-sign-out-alt"></i>Comments</a>
            <h3 class="text-center">
                @ViewBag.Film.Description
            </h3>
        </div>
    </div>
</div>


@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

07. Software Development/Solutions/Movie Mania/MovieMania/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page"; 
}

<body id="backgroundImage">
    <div class="text-center" id="headText">
        <h1 class="display-4">Movie Mania</h1>
        <h2>Here you can add you favourite movies or series which you've already watched and rate them.</h2>
    </div>
</body>

07. Software Development/Solutions/Movie Mania/MovieMania/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head class="header">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Movie Mania</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" id="navBarFont" asp-area="" asp-controller="Home" asp-action="Index">Movie Mania</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <!--
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                        -->
                        <li class="nav-item">
                            <a class="nav-link text-white btn-white" asp-area="" asp-controller="Catalog" asp-action="CatalogIndex">Catalog</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!--
        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2021 - MovieMania - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
    -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>